// Copyright 2025 IBM Corp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package main provides a tool for analyzing OpenShift CI job history from Prow.
// It fetches job data, parses build logs, and generates reports on deployment
// success rates and test failures for PowerVC-based CI runs.
package main

import (
	"compress/gzip"
	"compress/zlib"
	"context"
	"encoding/csv"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/http/cookiejar"
	"net/url"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
)

var (
	// version is the build version, replaced at build time with:
	//   -ldflags="-X main.version=$(git describe --always --long --dirty)"
	version = "undefined"

	// release is the release tag, replaced at build time with:
	//   -ldflags="-X main.release=$(git describe --tags --abbrev=0)"
	release = "undefined"
)

// HTTP client configuration constants
const (
	defaultHTTPTimeout = 30 * time.Second
	maxRetries         = 3
	retryDelay         = 2 * time.Second
)

// Global file handles for output streams
var (
	outputFp = os.Stdout // Primary output destination (results, CSV data)
	infoFp   = os.Stderr // Informational/diagnostic messages
)

// Common errors
var (
	ErrInvalidURL       = errors.New("invalid URL format")
	ErrInvalidDateRange = errors.New("invalid date range")
	ErrHTTPRequest      = errors.New("HTTP request failed")
	ErrParseJSON        = errors.New("failed to parse JSON")
	ErrParseHTML        = errors.New("failed to parse HTML")
)

// CIStats tracks aggregate statistics across all processed CI runs.
// It maintains counters for deployment attempts, successes, and fully green test runs.
type CIStats struct {
	NumDeploys       int // Total number of deployment attempts processed
	DeploysSucceeded int // Number of successful cluster deployments
	GreenRuns        int // Number of runs with all tests passing (no failures)
}

// SpyglassLink represents a single CI job entry from the Prow job history page.
// This structure is parsed from the JavaScript 'allBuilds' array embedded in the HTML.
type SpyglassLink struct {
	SpyglassLink string      `json:"SpyglassLink"` // Relative URL path to the Spyglass job viewer
	ID           string      `json:"ID"`           // Unique job identifier
	Started      string      `json:"Started"`      // Human-readable start time
	Duration     int64       `json:"Duration"`     // Job duration in seconds
	Result       string      `json:"Result"`       // Overall job result (SUCCESS, FAILURE, etc.)
	Refs         interface{} `json:"Refs"`         // Git references (branch, PR info)
}

// ConfFinished represents the structure of the finished.json artifact file.
// This file is created by Prow at the end of each job step to record its outcome.
type ConfFinished struct {
	Result string `json:"result"` // Step result: SUCCESS, FAILURE, ABORTED, etc.
}

// BuildFinished represents the structure of the finished.json artifact file.
// This file is created by Prow at the end of each job step to record its outcome.
type BuildFinished struct {
	Result string `json:"result"` // Step result: SUCCESS, FAILURE, ABORTED, etc.
}

// StartedJSON represents the structure of the started.json artifact file.
// This file contains the Unix timestamp when a job step began execution.
type StartedJSON struct {
	Timestamp int64 `json:"timestamp"` // Unix epoch timestamp (seconds since 1970-01-01)
}

// TestFailureSummary represents the structure of test-failures-summary_*.json files.
// These files are generated by the test framework and list all failed test cases.
type TestFailureSummary struct {
	Tests []struct {
		Test struct {
			Name string `json:"Name"` // Full test case name (e.g., "[sig-network] DNS should resolve...")
		} `json:"Test"`
	} `json:"Tests"` // Array of failed test entries
}

// HTTPClient wraps http.Client with context support and retry logic
type HTTPClient struct {
	client *http.Client
}

// NewHTTPClient creates a new HTTP client configured for Prow CI interactions.
// It initializes a cookie jar for session management and sets a default timeout
// to prevent hanging requests. The client is suitable for making multiple
// sequential requests to the same domain with session persistence.
//
// Returns:
//   - *HTTPClient: Configured HTTP client wrapper
//   - error: Error if cookie jar creation fails
func NewHTTPClient() (*HTTPClient, error) {
	jar, err := cookiejar.New(nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create cookie jar: %w", err)
	}

	return &HTTPClient{
		client: &http.Client{
			Jar:     jar,
			Timeout: defaultHTTPTimeout,
		},
	}, nil
}

// Get performs an HTTP GET request with context support and timeout handling.
// It creates a new request with the provided context, allowing for cancellation
// and deadline enforcement. The method validates the response status code and
// automatically closes the response body on error.
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - urlStr: Target URL to fetch
//
// Returns:
//   - *http.Response: HTTP response (caller must close Body)
//   - error: ErrHTTPRequest if request fails or status is not 200 OK
func (c *HTTPClient) Get(ctx context.Context, urlStr string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, urlStr, nil)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrHTTPRequest, err)
	}

	resp, err := c.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrHTTPRequest, err)
	}

	if resp.StatusCode != http.StatusOK {
		resp.Body.Close()
		return nil, fmt.Errorf("%w: status code %d", ErrHTTPRequest, resp.StatusCode)
	}

	return resp, nil
}

// getURLString fetches content from the specified URL and returns it as a string.
// It handles HTTP compression (gzip, deflate) and sanitizes invalid UTF-8 characters
// that may appear in CI logs. The function validates the URL before making the request
// and properly handles compressed response bodies.
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - client: HTTP client to use for the request
//   - urlStr: Target URL to fetch
//
// Returns:
//   - string: Response body as a sanitized UTF-8 string
//   - error: ErrInvalidURL if URL is malformed, or HTTP/decompression errors
//
// The function replaces invalid UTF-8 characters (\x80-\x83) with spaces to
// prevent encoding issues when parsing CI logs.
func getURLString(ctx context.Context, client *HTTPClient, urlStr string) (string, error) {
	if err := validateURL(urlStr); err != nil {
		return "", err
	}

	resp, err := client.Get(ctx, urlStr)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	data, err := getData(resp)
	if err != nil {
		return "", err
	}

	// Handle potential encoding issues - sanitize invalid UTF-8 characters
	str := string(data)
	replacements := []string{"\x80", "\x81", "\x82", "\x83"}
	for _, r := range replacements {
		str = strings.ReplaceAll(str, r, " ")
	}

	return str, nil
}

// validateURL checks if the URL is valid and properly formatted.
// It ensures the URL is not empty, can be parsed, and uses HTTP/HTTPS scheme.
// This validation helps catch configuration errors early before making requests.
//
// Parameters:
//   - urlStr: URL string to validate
//
// Returns:
//   - error: ErrInvalidURL with details if validation fails, nil if valid
func validateURL(urlStr string) error {
	if urlStr == "" {
		return fmt.Errorf("%w: empty URL", ErrInvalidURL)
	}

	parsedURL, err := url.Parse(urlStr)
	if err != nil {
		return fmt.Errorf("%w: %v", ErrInvalidURL, err)
	}

	if parsedURL.Scheme != "https" && parsedURL.Scheme != "http" {
		return fmt.Errorf("%w: invalid scheme %s", ErrInvalidURL, parsedURL.Scheme)
	}

	return nil
}

// getData handles compressed response data from HTTP responses.
// It automatically detects and decompresses gzip, x-gzip, and deflate encodings.
// For deflate, it attempts zlib decompression first, then falls back to raw deflate.
//
// Parameters:
//   - resp: HTTP response with potential compressed body
//
// Returns:
//   - []byte: Decompressed response body
//   - error: Error if decompression fails or encoding is unknown
//
// Supported encodings: gzip, x-gzip, deflate, or uncompressed (empty encoding)
func getData(resp *http.Response) ([]byte, error) {
	encoding := resp.Header.Get("Content-Encoding")

	switch encoding {
	case "gzip", "x-gzip":
		reader, err := gzip.NewReader(resp.Body)
		if err != nil {
			return nil, fmt.Errorf("failed to create gzip reader: %w", err)
		}
		defer reader.Close()
		return io.ReadAll(reader)

	case "deflate":
		reader, err := zlib.NewReader(resp.Body)
		if err != nil {
			// Try raw deflate as fallback
			data, readErr := io.ReadAll(resp.Body)
			if readErr != nil {
				return nil, fmt.Errorf("failed to read deflate data: %w", readErr)
			}
			return data, nil
		}
		defer reader.Close()
		return io.ReadAll(reader)

	case "":
		return io.ReadAll(resp.Body)

	default:
		return nil, fmt.Errorf("unknown content encoding: %s", encoding)
	}
}

// getZone extracts the PowerVS zone identifier from a CI job's build log.
// It parses the build-log.txt file to find the lease acquisition message that
// indicates which PowerVS zone was allocated for the test run. This information
// is useful for tracking which zones are being used and correlating failures
// with specific infrastructure locations.
//
// The function searches for a log line matching the pattern:
//   "Acquired 1 lease(s) for powervs-[1-9]-quota-slice: [zone-name]"
//
// For example, if the log contains:
//   "Acquired 1 lease(s) for powervs-1-quota-slice: [dal-10]"
// The function will return "dal-10".
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - client: HTTP client to use for fetching the build log
//   - spyglassLink: Job metadata containing the Spyglass link path to construct the log URL
//   - ciTypeStr: CI type identifier (currently unused, reserved for future use)
//
// Returns:
//   - string: The zone identifier (e.g., "dal-10", "lon-06") if found, empty string if not found
//   - error: Error if the build log cannot be fetched or HTTP request fails
//
// Note: This function returns an empty string (not an error) if the lease acquisition
// pattern is not found in the log, which may occur for jobs that failed before
// acquiring a zone lease or for non-PowerVS CI jobs.
func getZone(ctx context.Context, client *HTTPClient, spyglassLink SpyglassLink, ciTypeStr string) (string, error) {
	zoneLogURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/build-log.txt"
	zoneLogStr, err := getURLString(ctx, client, zoneLogURL)
	if err != nil {
		return "", err
	}

	zoneLogRe := regexp.MustCompile(`Acquired 1 lease\(s\) for powervs-[1-9]-quota-slice: \[([^\]]+)\]`)
	matches := zoneLogRe.FindStringSubmatch(zoneLogStr)
	if matches == nil {
		return "", nil
	}

	return matches[1], nil
}

// includeWithDate checks if a CI job should be included based on date range filtering.
// It fetches the job's started.json file to determine when the job began, then compares
// this timestamp against the specified date range. Jobs without valid started.json files
// (incomplete or failed jobs) will return an error.
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - client: HTTP client to use for fetching metadata
//   - afterDt: Start of date range (inclusive)
//   - beforeDt: End of date range (inclusive)
//   - spyglassLink: Job metadata containing the Spyglass link path
//
// Returns:
//   - bool: true if job falls within date range, false otherwise
//   - error: Error if started.json cannot be fetched or parsed, or if link is invalid
func includeWithDate(ctx context.Context, client *HTTPClient, afterDt, beforeDt time.Time, spyglassLink SpyglassLink) (bool, error) {
	if spyglassLink.SpyglassLink == "" {
		return false, fmt.Errorf("empty spyglass link")
	}

	if len(spyglassLink.SpyglassLink) < 8 {
		return false, fmt.Errorf("invalid spyglass link format")
	}

	startedURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/started.json"
	startedStr, err := getURLString(ctx, client, startedURL)
	if err != nil {
		return false, fmt.Errorf("failed to fetch started.json: %w", err)
	}

	var startedJSON StartedJSON
	if err := json.Unmarshal([]byte(startedStr), &startedJSON); err != nil {
		return false, fmt.Errorf("%w: %v", ErrParseJSON, err)
	}

	if startedJSON.Timestamp <= 0 {
		return false, fmt.Errorf("invalid timestamp: %d", startedJSON.Timestamp)
	}

	startedDt := time.Unix(startedJSON.Timestamp, 0).UTC()
	return (startedDt.After(afterDt) && startedDt.Before(beforeDt)) || startedDt.Equal(afterDt) || startedDt.Equal(beforeDt), nil
}

// gatherConfRun gathers build/conf information for a CI job.
// It fetches the finished.json file to determine if the cluster configuration succeeded,
// and if it failed, extracts the failure details from the build log. The function
// looks for specific markers in the build log to extract the relevant error section.
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - client: HTTP client to use for fetching artifacts
//   - spyglassLink: Job metadata containing the Spyglass link path
//   - ciTypeStr: CI type identifier (e.g., "powervc-1") for constructing artifact paths
//
// Returns:
//   - ConfFinished: Parsed finished.json with result status
//   - string: Conf summary message (SUCCESS/FAILURE with description)
//   - string: Detailed error output from build log (empty if successful)
//   - error: Error if artifacts cannot be fetched or CI type is invalid
func gatherConfRun(ctx context.Context, client *HTTPClient, spyglassLink SpyglassLink, ciTypeStr string) (ConfFinished, string, string, error) {
	confFinished := ConfFinished{Result: "FAILURE"}
	confSummaryStr := ""
	confDetailsStr := ""

	if ciTypeStr == "" {
		return confFinished, confSummaryStr, confDetailsStr, fmt.Errorf("empty CI type string")
	}

	finishedURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/ipi-install-powervc-install/finished.json"
	finishedStr, err := getURLString(ctx, client, finishedURL)
	if err == nil && !strings.Contains(finishedStr, "<!doctype html>") {
		if err := json.Unmarshal([]byte(finishedStr), &confFinished); err != nil {
			fmt.Fprintf(infoFp, "WARN: Failed to parse finished.json: %v\n", err)
		}
	}

	if confFinished.Result == "SUCCESS" {
		confSummaryStr = "SUCCESS: conf succeeded!"
		return confFinished, confSummaryStr, confDetailsStr, nil
	}

	buildLogURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/ipi-conf-powervc/build-log.txt"

	buildLogStr, err := getURLString(ctx, client, buildLogURL)
	if err != nil {
		return confFinished, confSummaryStr, confDetailsStr, fmt.Errorf("failed to fetch conf log: %w", err)
	}

	//imageExistsRe := regexp.MustCompile(`Checking if (.*) exists in PowerVC`)
	imageExistsRe := regexp.MustCompile(`ERROR: RHCOS image '(.*)' not found in PowerVC cloud`)
	matches := imageExistsRe.FindStringSubmatch(buildLogStr)

	if len(matches) >= 2 {
		confSummaryStr = "FAILURE: conf failed!"
		confDetailsStr = matches[0]
	} else {
		confSummaryStr = "FAILURE: Could not find conf?"
	}

	return confFinished, confSummaryStr, confDetailsStr, nil
}

// gatherBuildRun gathers build/deployment information for a CI job.
// It fetches the finished.json file to determine if the cluster deployment succeeded,
// and if it failed, extracts the failure details from the build log. The function
// looks for specific markers in the build log to extract the relevant error section.
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - client: HTTP client to use for fetching artifacts
//   - spyglassLink: Job metadata containing the Spyglass link path
//   - ciTypeStr: CI type identifier (e.g., "powervc-1") for constructing artifact paths
//
// Returns:
//   - BuildFinished: Parsed finished.json with result status
//   - string: Build summary message (SUCCESS/FAILURE with description)
//   - string: Detailed error output from build log (empty if successful)
//   - error: Error if artifacts cannot be fetched or CI type is invalid
func gatherBuildRun(ctx context.Context, client *HTTPClient, spyglassLink SpyglassLink, ciTypeStr string) (BuildFinished, string, string, error) {
	buildFinished := BuildFinished{Result: "FAILURE"}
	buildSummaryStr := ""
	buildDetailsStr := ""

	if ciTypeStr == "" {
		return buildFinished, buildSummaryStr, buildDetailsStr, fmt.Errorf("empty CI type string")
	}

	finishedURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/ipi-install-powervc-install/finished.json"
	finishedStr, err := getURLString(ctx, client, finishedURL)
	if err == nil && !strings.Contains(finishedStr, "<!doctype html>") {
		if err := json.Unmarshal([]byte(finishedStr), &buildFinished); err != nil {
			fmt.Fprintf(infoFp, "WARN: Failed to parse finished.json: %v\n", err)
		}
	}

	if buildFinished.Result == "SUCCESS" {
		buildSummaryStr = "SUCCESS: create cluster succeeded!"
		return buildFinished, buildSummaryStr, buildDetailsStr, nil
	}

	buildLogURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/ipi-install-powervc-install/build-log.txt"
	buildLogStr, err := getURLString(ctx, client, buildLogURL)
	if err != nil {
		return buildFinished, buildSummaryStr, buildDetailsStr, fmt.Errorf("failed to fetch build log: %w", err)
	}

	createClusterRe := regexp.MustCompile(`(?s)8<--------8<--------8<--------8<-------- BEGIN: create cluster 8<--------8<--------8<--------8<--------\n(.*?)8<--------8<--------8<--------8<-------- END: create cluster 8<--------8<--------8<--------8<--------\n`)
	matches := createClusterRe.FindStringSubmatch(buildLogStr)
	if len(matches) >= 2 {
		buildSummaryStr = "FAILURE: create cluster failed!"
		buildDetailsStr = matches[1]
	} else {
		buildSummaryStr = "FAILURE: Could not find create cluster?"
	}

	return buildFinished, buildSummaryStr, buildDetailsStr, nil
}

// gatherTestRun gathers test execution results for a CI job.
// It fetches the test-failures-summary JSON file from the junit artifacts directory
// to determine which tests failed. If all tests passed, it increments the green runs
// counter in the statistics. The function searches for the summary file using a regex
// pattern since the filename includes a timestamp.
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - client: HTTP client to use for fetching artifacts
//   - spyglassLink: Job metadata containing the Spyglass link path
//   - ciTypeStr: CI type identifier for constructing artifact paths
//   - ciStats: Statistics tracker to update (increments GreenRuns on success)
//
// Returns:
//   - string: Test summary message (SUCCESS/FAILURE/ERROR with description)
//   - string: Detailed list of failed test names (empty if all passed)
//   - error: Error if artifacts cannot be fetched or CI type is invalid
func gatherTestRun(ctx context.Context, client *HTTPClient, spyglassLink SpyglassLink, ciTypeStr string, ciStats *CIStats) (string, string, error) {
	testSummaryStr := ""
	testDetailsStr := ""

	if ciTypeStr == "" {
		return testSummaryStr, testDetailsStr, fmt.Errorf("empty CI type string")
	}

	junitDirURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/openshift-e2e-libvirt-test/artifacts/junit/"
	junitDirStr, err := getURLString(ctx, client, junitDirURL)
	if err != nil {
		return testSummaryStr, testDetailsStr, fmt.Errorf("failed to fetch junit directory: %w", err)
	}

	filenameRe := regexp.MustCompile(`test-failures-summary_[^.]*\.json`)
	matches := filenameRe.FindStringSubmatch(junitDirStr)
	if len(matches) == 0 {
		testSummaryStr = "ERROR: Could not find test-failures-summary_*.json?"
		return testSummaryStr, testDetailsStr, nil
	}

	testFailureFilename := matches[0]
	junitURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/openshift-e2e-libvirt-test/artifacts/junit/" + testFailureFilename
	junitStr, err := getURLString(ctx, client, junitURL)
	if err != nil {
		return testSummaryStr, testDetailsStr, fmt.Errorf("failed to fetch test failures: %w", err)
	}

	var testFailureSummary TestFailureSummary
	if err := json.Unmarshal([]byte(junitStr), &testFailureSummary); err != nil {
		return testSummaryStr, testDetailsStr, fmt.Errorf("%w: %v", ErrParseJSON, err)
	}

	if len(testFailureSummary.Tests) == 0 {
		testSummaryStr = "SUCCESS: All tests succeeded!"
		ciStats.GreenRuns++
	} else {
		testSummaryStr = "FAILURE: Failing tests:"
		for _, test := range testFailureSummary.Tests {
			testDetailsStr += test.Test.Name + "\n"
		}
	}

	return testSummaryStr, testDetailsStr, nil
}

// fromISOFormat attempts to parse a date string using multiple ISO 8601 formats.
// It tries formats with varying precision (microseconds, seconds, date-only) to
// accommodate different input styles from command-line arguments.
// This flexibility allows users to specify dates as "2023-07-20" or "2023-07-20T15:04:05Z".
// Returns the parsed time in UTC, or an error if no format matches.
func fromISOFormat(dateStr string) (time.Time, error) {
	if dateStr == "" {
		return time.Time{}, fmt.Errorf("empty date string")
	}

	formats := []string{
		"2006-01-02T15:04:05.999999Z",
		"2006-01-02T15:04:05Z",
		"2006-01-02T15:04:05.999999",
		"2006-01-02T15:04:05",
		"2006-01-02",
	}

	for _, format := range formats {
		t, err := time.Parse(format, dateStr)
		if err == nil {
			return t.UTC(), nil
		}
	}

	return time.Time{}, fmt.Errorf("unable to parse date: %s", dateStr)
}

// encodeString prepares a string for CSV output by escaping newline characters.
// CSV format doesn't handle multi-line cell content well, so newlines are converted
// to the literal string "\n" to keep each record on a single line.
// This ensures proper CSV parsing by spreadsheet applications like Excel and Google Sheets.
//
// Parameters:
//   - input: String to encode (may contain newlines)
//
// Returns:
//   - string: Encoded string with newlines replaced by literal "\n"
func encodeString(input string) string {
	return strings.ReplaceAll(input, "\n", "\\n")
}

// processURL processes a single Prow CI job history URL and extracts job data.
// This is the main processing function that orchestrates the entire data collection workflow:
// 1. Validates and parses the URL to extract CI version and type information
// 2. Iterates through job history pages (following "Older Runs" pagination links)
// 3. Filters jobs by date range using started.json timestamps
// 4. Collects build and test results for each matching job
// 5. Outputs results in either human-readable or CSV format
// 6. Updates aggregate statistics (deploys succeeded, green runs)
//
// The function continues pagination until no more jobs match the date criteria or
// no "Older Runs" link is found. It handles context cancellation gracefully and
// silently skips jobs with missing metadata (incomplete/failed jobs).
//
// Parameters:
//   - ctx: Context for cancellation and timeout control
//   - args: Command-line arguments controlling output format and filtering
//   - ciStats: Statistics tracker to update with job results
//   - urlStr: Prow job history URL to process
//   - afterDt: Start of date range filter (inclusive)
//   - beforeDt: End of date range filter (inclusive)
//   - csvWriter: CSV writer for output (nil if not in CSV mode)
//
// Returns:
//   - error: Error if URL is invalid, parsing fails, or HTTP requests fail
func processURL(ctx context.Context, args *Args, ciStats *CIStats, urlStr string, afterDt, beforeDt time.Time, csvWriter *csv.Writer) error {
	fmt.Fprintf(infoFp, "INFO: For URL %s\n", urlStr)
	fmt.Fprintf(infoFp, "INFO: Finding CI runs between %s and %s\n", afterDt.Format(time.RFC3339), beforeDt.Format(time.RFC3339))
	fmt.Fprintln(infoFp)

	// Validate and parse URL
	if err := validateURL(urlStr); err != nil {
		return err
	}

	// Remove trailing slash if present
	urlStr = strings.TrimSuffix(urlStr, "/")
	parts := strings.Split(urlStr, "/")
	if len(parts) < 3 {
		return fmt.Errorf("%w: insufficient URL parts", ErrInvalidURL)
	}

	baseURLStr := parts[0] + "//" + parts[2]
	idx := strings.LastIndex(urlStr, "/")
	if idx == -1 {
		return fmt.Errorf("%w: no path separator found", ErrInvalidURL)
	}
	ciStr := urlStr[idx+1:]

	// Extract CI version (e.g., "4.12", "5.0") and type (e.g., "powervc-1") from job name
	ciInfoRe := regexp.MustCompile(`([^0-9].*)-([0-9]+\.[0-9]+)-(.*)`)
	matches := ciInfoRe.FindStringSubmatch(ciStr)
	if len(matches) < 4 {
		return fmt.Errorf("failed to parse CI string: %s", ciStr)
	}

	ciVersionStr := matches[2] // OpenShift version (e.g., "4.12", "4.13")
	ciTypeStr := matches[3]    // CI type/platform (e.g., "powervc-1", "powervc-2")

	// Create HTTP client
	client, err := NewHTTPClient()
	if err != nil {
		return fmt.Errorf("failed to create HTTP client: %w", err)
	}

	// Main pagination loop: process current page, then follow "Older Runs" link
	for {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
		}

		processedAny := false // Track if we processed any jobs on this page

		resp, err := client.Get(ctx, urlStr)
		if err != nil {
			return err
		}

		doc, err := goquery.NewDocumentFromReader(resp.Body)
		resp.Body.Close()
		if err != nil {
			return fmt.Errorf("%w: %v", ErrParseHTML, err)
		}

		// Find the "Older Runs" pagination link
		var olderHref string
		doc.Find("td").Each(func(i int, s *goquery.Selection) {
			if strings.Contains(s.Text(), "Older Runs") {
				s.Find("a").Each(func(j int, a *goquery.Selection) {
					if href, exists := a.Attr("href"); exists {
						olderHref = href
					}
				})
			}
		})

		// Find and process the allBuilds JavaScript array
		doc.Find("script").Each(func(i int, s *goquery.Selection) {
			scriptText := s.Text()
			if !strings.Contains(scriptText, "var allBuilds") {
				return
			}

			tableRe := regexp.MustCompile(`var allBuilds = (\[[^\]]+\]);`)
			matches := tableRe.FindStringSubmatch(scriptText)
			if len(matches) < 2 {
				return
			}

			var spyglassLinks []SpyglassLink
			if err := json.Unmarshal([]byte(matches[1]), &spyglassLinks); err != nil {
				fmt.Fprintf(infoFp, "WARN: Failed to parse allBuilds: %v\n", err)
				return
			}

			// Process each job entry
			for _, spyglassLink := range spyglassLinks {
				select {
				case <-ctx.Done():
					return
				default:
				}

				buildSummaryStr := ""
				buildDetailsStr := ""
				testSummaryStr := ""
				testDetailsStr := ""

				// Construct full Spyglass URL
				jobURL := "https://prow.ci.openshift.org" + spyglassLink.SpyglassLink

				// Filter by date range
				include, err := includeWithDate(ctx, client, afterDt, beforeDt, spyglassLink)
				if err != nil {
					// Silently skip jobs that don't have started.json or return HTML errors (incomplete/failed jobs)
					// These are expected for jobs that haven't completed or failed early
					errStr := err.Error()
					if !strings.Contains(errStr, "status code 404") &&
					   !strings.Contains(errStr, "failed to fetch started.json") &&
					   !strings.Contains(errStr, "failed to parse JSON") &&
					   !strings.Contains(errStr, "invalid character '<'") {
						fmt.Fprintf(infoFp, "WARN: Failed to check date for job %s: %v\n", jobURL, err)
					}
					continue
				}
				if !include {
					continue
				}

				// Job passed all filters - process it
				processedAny = true
				ciStats.NumDeploys++

				// Print job header
				fmt.Fprintf(infoFp, "INFO: 8<--------8<--------8<--------8<--------8<--------8<--------8<--------8<--------\n")
				fmt.Fprintf(infoFp, "INFO: URL:  %s\n", jobURL)

				// Gather deployment/conf results
				confFinished, confSummaryStr, confDetailsStr, err := gatherConfRun(ctx, client, spyglassLink, ciTypeStr)
				if err != nil {
					fmt.Fprintf(infoFp, "WARN: Failed to gather conf run: %v\n", err)
					continue
				}

				// Output build results unless user only wants test status
				if !args.TestStatusOnly {
					if !args.CSV {
						fmt.Fprintf(outputFp, "%s\n%s\n", confSummaryStr, confDetailsStr)
					}
				}

				// If conf succeeded,
				if confFinished.Result == "SUCCESS" {
				} else {
				}

				// Gather deployment/build results
				buildFinished, buildSummaryStr, buildDetailsStr, err := gatherBuildRun(ctx, client, spyglassLink, ciTypeStr)
				if err != nil {
					fmt.Fprintf(infoFp, "WARN: Failed to gather build run: %v\n", err)
					continue
				}

				// Output build results unless user only wants test status
				if !args.TestStatusOnly {
					if !args.CSV {
						fmt.Fprintf(outputFp, "%s\n%s", buildSummaryStr, buildDetailsStr)
					}
				}

				// If deployment succeeded, gather test results
				if buildFinished.Result == "SUCCESS" {
					ciStats.DeploysSucceeded++

					if !args.DeployStatusOnly {
						testSummaryStr, testDetailsStr, err = gatherTestRun(ctx, client, spyglassLink, ciTypeStr, ciStats)
						if err != nil {
							fmt.Fprintf(infoFp, "WARN: Failed to gather test run: %v\n", err)
						} else if !args.CSV {
							fmt.Fprintf(outputFp, "%s\n%s\n", testSummaryStr, testDetailsStr)
						}
					} else {
						fmt.Fprintln(outputFp)
					}
				} else {
					if !args.CSV {
						fmt.Fprintln(outputFp)
					}
				}

				// Write CSV row if CSV output is enabled
				if args.CSV {
					testDetailsStr = strings.TrimSuffix(testDetailsStr, "\n")
					csvRow := []string{
						encodeString(jobURL),
						encodeString(buildSummaryStr),
						encodeString(buildDetailsStr),
						encodeString(testSummaryStr),
						encodeString(testDetailsStr),
					}
					if err := csvWriter.Write(csvRow); err != nil {
						fmt.Fprintf(infoFp, "WARN: Failed to write CSV row: %v\n", err)
					}
					fmt.Fprintln(infoFp)
				}
			}
		})

		// Stop pagination if no "Older Runs" link exists
		if olderHref == "" {
			break
		}

		// Stop pagination if we didn't process any jobs on this page
		if !processedAny {
			break
		}

		// Continue to the next page
		urlStr = baseURLStr + olderHref
	}

	_ = ciVersionStr // Suppress unused variable warning

	return nil
}

// Args holds all command-line arguments and configuration options.
type Args struct {
	AfterStr         string   // Start date for filtering jobs (ISO 8601 format)
	BeforeStr        string   // End date for filtering jobs (ISO 8601 format)
	CSV              bool     // Enable CSV output format
	DeployStatusOnly bool     // Only report deployment status (skip test results)
	LastNDays        int      // Filter to last N days (alternative to AfterStr/BeforeStr)
	Output           string   // Output file path (empty = stdout)
	TestStatusOnly   bool     // Only report test status (skip deployment details)
	Today            bool     // Filter to today's jobs only
	URLs             []string // List of Prow job history URLs to process
	Yesterday        bool     // Filter to yesterday's jobs only
}

// main is the entry point for the JobHistory tool.
// It parses command-line arguments, validates date ranges, processes each CI URL,
// and outputs aggregated statistics about deployment success and test pass rates.
// parseAndValidateArgs parses command-line arguments and validates them.
// It sets up flag definitions, parses the command line, validates the arguments,
// and calculates the date range based on the provided options.
//
// Returns:
//   - *Args: Parsed and validated arguments
//   - time.Time: Start date for filtering (afterDt)
//   - time.Time: End date for filtering (beforeDt)
//   - error: Error if validation fails, nil otherwise
func parseAndValidateArgs() (*Args, time.Time, time.Time, error) {
	args := &Args{}

	// Custom usage function
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [OPTIONS] URL [URL...]\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Analyze OpenShift CI job history from Prow for PowerVC deployments.\n\n")
		fmt.Fprintf(os.Stderr, "Required Arguments:\n")
		fmt.Fprintf(os.Stderr, "  URL    One or more Prow job history URLs to analyze\n")
		fmt.Fprintf(os.Stderr, "         Format: https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/<job-name>\n\n")
		fmt.Fprintf(os.Stderr, "Options (must be specified BEFORE URLs):\n")
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\nExamples:\n")
		fmt.Fprintf(os.Stderr, "  # Analyze today's jobs\n")
		fmt.Fprintf(os.Stderr, "  %s --today https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/periodic-ci-...\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  # Analyze last 7 days with CSV output\n")
		fmt.Fprintf(os.Stderr, "  %s --last-n-days 7 --csv --output results.csv <URL>\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Note: All options must be specified before the URL(s).\n")
	}

	// Define command-line flags
	flag.StringVar(&args.AfterStr, "after-date", "", "Only queries after this date (ISO 8601 format)")
	flag.StringVar(&args.AfterStr, "a", "", "Only queries after this date (shorthand)")
	flag.StringVar(&args.BeforeStr, "before-date", "", "Only queries before this date (ISO 8601 format)")
	flag.StringVar(&args.BeforeStr, "b", "", "Only queries before this date (shorthand)")
	flag.BoolVar(&args.CSV, "csv", false, "Output in CSV format")
	flag.BoolVar(&args.CSV, "c", false, "Output in CSV format (shorthand)")
	flag.BoolVar(&args.DeployStatusOnly, "deploy-status-only", false, "Only show deploy failures")
	flag.BoolVar(&args.DeployStatusOnly, "d", false, "Only show deploy failures (shorthand)")
	flag.IntVar(&args.LastNDays, "last-n-days", 0, "Only queries for the last n days")
	flag.IntVar(&args.LastNDays, "l", 0, "Only queries for the last n days (shorthand)")
	flag.StringVar(&args.Output, "output", "", "The filename for output")
	flag.StringVar(&args.Output, "o", "", "The filename for output (shorthand)")
	flag.BoolVar(&args.TestStatusOnly, "test-status-only", false, "Only show test failures")
	flag.BoolVar(&args.TestStatusOnly, "t", false, "Only show test failures (shorthand)")
	flag.BoolVar(&args.Today, "today", false, "Only queries for today")
	flag.BoolVar(&args.Yesterday, "yesterday", false, "Only queries for yesterday")

	showVersion := flag.Bool("version", false, "Display the version of this program")
	flag.BoolVar(showVersion, "v", false, "Display the version of this program (shorthand)")

	flag.Parse()

	// Handle version flag
	if *showVersion {
		fmt.Printf("Program version is %v, release = %v\n", version, release)
		os.Exit(0)
	}

	// Collect positional arguments as URLs
	args.URLs = flag.Args()
	if len(args.URLs) == 0 {
		return nil, time.Time{}, time.Time{}, fmt.Errorf("at least one URL is required")
	}

	// Check if any positional arguments look like flags
	for _, arg := range args.URLs {
		if strings.HasPrefix(arg, "-") || strings.HasPrefix(arg, "--") {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("flag '%s' appears after URL(s); all options must be specified BEFORE the URL arguments", arg)
		}
	}

	// Date range validation and calculation
	var afterDt, beforeDt time.Time
	var err error

	if args.Today {
		if args.AfterStr != "" || args.BeforeStr != "" || args.Yesterday || args.LastNDays > 0 {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("cannot combine --today with other date options")
		}
		now := time.Now().UTC()
		afterDt = time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
		beforeDt = time.Date(now.Year(), now.Month(), now.Day(), 23, 59, 59, 999999999, time.UTC)
	} else if args.Yesterday {
		if args.AfterStr != "" || args.BeforeStr != "" || args.Today || args.LastNDays > 0 {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("cannot combine --yesterday with other date options")
		}
		yesterday := time.Now().UTC().AddDate(0, 0, -1)
		afterDt = time.Date(yesterday.Year(), yesterday.Month(), yesterday.Day(), 0, 0, 0, 0, time.UTC)
		beforeDt = time.Date(yesterday.Year(), yesterday.Month(), yesterday.Day(), 23, 59, 59, 999999999, time.UTC)
	} else if args.LastNDays > 0 {
		if args.Today || args.Yesterday {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("cannot combine --last-n-days with other date options")
		}
		if args.LastNDays < 1 {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("--last-n-days must be at least 1")
		}
		lastDate := time.Now().UTC().AddDate(0, 0, -(args.LastNDays - 1))
		afterDt = time.Date(lastDate.Year(), lastDate.Month(), lastDate.Day(), 0, 0, 0, 0, time.UTC)
		now := time.Now().UTC()
		beforeDt = time.Date(now.Year(), now.Month(), now.Day(), 23, 59, 59, 999999999, time.UTC)
	} else {
		// Default: no start date, end date is now
		afterDt = time.Time{}
		beforeDt = time.Now().UTC()
	}

	// Override with explicit dates if provided
	if args.AfterStr != "" {
		afterDt, err = fromISOFormat(args.AfterStr)
		if err != nil {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("invalid after-date format: %w", err)
		}
	}

	if args.BeforeStr != "" {
		beforeDt, err = fromISOFormat(args.BeforeStr)
		if err != nil {
			return nil, time.Time{}, time.Time{}, fmt.Errorf("invalid before-date format: %w", err)
		}
	}

	// Validate date range
	if !afterDt.IsZero() && !beforeDt.IsZero() && afterDt.After(beforeDt) {
		return nil, time.Time{}, time.Time{}, fmt.Errorf("after-date must be before before-date")
	}

	return args, afterDt, beforeDt, nil
}

// main is the entry point for the JobHistory program.
// It analyzes OpenShift CI job history from Prow for PowerVC deployments.
//
// The program performs the following steps:
//  1. Parses and validates command-line arguments
//  2. Sets up output file and CSV writer if requested
//  3. Initializes statistics tracking
//  4. Processes each provided Prow job history URL
//  5. Prints summary statistics of deployment and test results
//
// The program supports various filtering options:
//   - Date range filtering (--after-date, --before-date, --today, --yesterday, --last-n-days)
//   - Output format options (--csv, --output)
//   - Result filtering (--deploy-status-only, --test-status-only)
//
// Exit codes:
//   - 0: Success
//   - 1: Error (invalid arguments, file I/O error, or processing error)
func main() {
	// Parse and validate arguments
	args, afterDt, beforeDt, err := parseAndValidateArgs()
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
		flag.Usage()
		os.Exit(1)
	}

	// Setup output file
	if args.Output != "" {
		f, err := os.Create(args.Output)
		if err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: Cannot create output file: %v\n", err)
			os.Exit(1)
		}
		defer f.Close()
		outputFp = f
		if !args.CSV {
			infoFp = f
		}
	}

	// Initialize CSV writer
	var csvWriter *csv.Writer
	if args.CSV {
		csvWriter = csv.NewWriter(outputFp)
		defer csvWriter.Flush()
		// Write CSV header (removed Zone column)
		if err := csvWriter.Write([]string{
			"Job URL",
			"Build summary",
			"Build details",
			"Test summary",
			"Test details",
		}); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: Failed to write CSV header: %v\n", err)
			os.Exit(1)
		}
	}

	// Initialize statistics tracker
	ciStats := &CIStats{}

	// Create context with cancellation
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Process each URL
	for _, urlStr := range args.URLs {
		// Validate URL format
		if !strings.Contains(urlStr, "https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/") {
			fmt.Fprintf(infoFp, "ERROR: Invalid CI URL format: %s\n", urlStr)
			fmt.Fprintln(infoFp, "Expected format: https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/<job-name>")
			os.Exit(1)
		}

		// Process this URL
		if err := processURL(ctx, args, ciStats, urlStr, afterDt, beforeDt, csvWriter); err != nil {
			fmt.Fprintf(infoFp, "ERROR: Failed to process URL %s: %v\n", urlStr, err)
		}
	}

	// Print final summary statistics
	fmt.Fprintln(infoFp, "Finished")
	if !args.TestStatusOnly {
		fmt.Fprintf(infoFp, "%d/%d deploys succeeded\n", ciStats.DeploysSucceeded, ciStats.NumDeploys)
	}
	if !args.DeployStatusOnly {
		fmt.Fprintf(infoFp, "%d/%d e2e green runs\n", ciStats.GreenRuns, ciStats.NumDeploys)
	}
}

// Made with Bob
