// Copyright 2025 IBM Corp
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package main provides a tool for analyzing OpenShift CI job history from Prow.
// It fetches job data, parses build logs, and generates reports on deployment
// success rates and test failures for PowerVC-based CI runs.
package main

import (
	"compress/gzip"
	"compress/zlib"
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"net/http/cookiejar"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
)

// Program metadata constants
const (
	version = "0.9.4"
	date    = "2023-07-20"
	author  = "Mark Hamzy (mhamzy@redhat.com)"
)

// Global file handles for output streams
var (
	outputFp = os.Stdout // Primary output destination (results, CSV data)
	infoFp   = os.Stderr // Informational/diagnostic messages
)

// CIStats tracks aggregate statistics across all processed CI runs.
// It maintains counters for deployment attempts, successes, and fully green test runs.
type CIStats struct {
	NumDeploys       int // Total number of deployment attempts processed
	DeploysSucceeded int // Number of successful cluster deployments
	GreenRuns        int // Number of runs with all tests passing (no failures)
}

// SpyglassLink represents a single CI job entry from the Prow job history page.
// This structure is parsed from the JavaScript 'allBuilds' array embedded in the HTML.
type SpyglassLink struct {
	SpyglassLink string      `json:"SpyglassLink"` // Relative URL path to the Spyglass job viewer
	ID           string      `json:"ID"`           // Unique job identifier
	Started      string      `json:"Started"`      // Human-readable start time
	Duration     int64       `json:"Duration"`     // Job duration in seconds
	Result       string      `json:"Result"`       // Overall job result (SUCCESS, FAILURE, etc.)
	Refs         interface{} `json:"Refs"`         // Git references (branch, PR info)
}

// BuildFinished represents the structure of the finished.json artifact file.
// This file is created by Prow at the end of each job step to record its outcome.
type BuildFinished struct {
	Result string `json:"result"` // Step result: SUCCESS, FAILURE, ABORTED, etc.
}

// StartedJSON represents the structure of the started.json artifact file.
// This file contains the Unix timestamp when a job step began execution.
type StartedJSON struct {
	Timestamp int64 `json:"timestamp"` // Unix epoch timestamp (seconds since 1970-01-01)
}

// TestFailureSummary represents the structure of test-failures-summary_*.json files.
// These files are generated by the test framework and list all failed test cases.
type TestFailureSummary struct {
	Tests []struct {
		Test struct {
			Name string `json:"Name"` // Full test case name (e.g., "[sig-network] DNS should resolve...")
		} `json:"Test"`
	} `json:"Tests"` // Array of failed test entries
}

// getURLString fetches content from the specified URL and returns it as a string.
// It handles HTTP compression (gzip, deflate) and sanitizes invalid UTF-8 characters
// that may appear in CI logs. The client parameter should have cookies enabled for
// session management across multiple requests.
func getURLString(client *http.Client, url string) (string, error) {
	resp, err := client.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	data, err := getData(resp)
	if err != nil {
		return "", err
	}

	// Handle potential encoding issues
	str := string(data)
	// Replace invalid characters
	replacements := []string{"\x80", "\x81", "\x82", "\x83"}
	for _, r := range replacements {
		str = strings.ReplaceAll(str, r, " ")
	}

	return str, nil
}

// getData handles compressed response data
func getData(resp *http.Response) ([]byte, error) {
	encoding := resp.Header.Get("Content-Encoding")

	switch encoding {
	case "gzip", "x-gzip":
		reader, err := gzip.NewReader(resp.Body)
		if err != nil {
			return nil, err
		}
		defer reader.Close()
		return io.ReadAll(reader)

	case "deflate":
		reader, err := zlib.NewReader(resp.Body)
		if err != nil {
			// Try raw deflate
			data, err := io.ReadAll(resp.Body)
			if err != nil {
				return nil, err
			}
			reader := io.NopCloser(strings.NewReader(string(data)))
			return io.ReadAll(reader)
		}
		defer reader.Close()
		return io.ReadAll(reader)

	case "":
		return io.ReadAll(resp.Body)

	default:
		return nil, fmt.Errorf("unknown content encoding: %s", encoding)
	}
}

// includeWithDate checks if the job should be included based on date range
func includeWithDate(client *http.Client, afterDt, beforeDt time.Time, spyglassLink SpyglassLink, ciTypeStr string) (bool, error) {
	startedURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/started.json"
	startedStr, err := getURLString(client, startedURL)
	if err != nil {
		return false, err
	}

	var startedJSON StartedJSON
	if err := json.Unmarshal([]byte(startedStr), &startedJSON); err != nil {
		return false, err
	}

	startedDt := time.Unix(startedJSON.Timestamp, 0).UTC()
	return startedDt.After(afterDt) && startedDt.Before(beforeDt) || startedDt.Equal(afterDt) || startedDt.Equal(beforeDt), nil
}

// gatherBuildRun gathers build run information
func gatherBuildRun(client *http.Client, spyglassLink SpyglassLink, ciTypeStr string) (BuildFinished, string, string, error) {
	buildFinished := BuildFinished{Result: "FAILURE"}
	buildSummaryStr := ""
	buildDetailsStr := ""

	finishedURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/ipi-install-powervc-install/finished.json"
	finishedStr, err := getURLString(client, finishedURL)
	if err == nil && !strings.Contains(finishedStr, "<!doctype html>") {
		json.Unmarshal([]byte(finishedStr), &buildFinished)
	}

	if buildFinished.Result == "SUCCESS" {
		buildSummaryStr = "SUCCESS: create cluster succeeded!"
		return buildFinished, buildSummaryStr, buildDetailsStr, nil
	}

	buildLogURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/ipi-install-powervc-install/build-log.txt"
	buildLogStr, err := getURLString(client, buildLogURL)
	if err != nil {
		return buildFinished, buildSummaryStr, buildDetailsStr, err
	}

	createClusterRe := regexp.MustCompile(`(?s)8<--------8<--------8<--------8<-------- BEGIN: create cluster 8<--------8<--------8<--------8<--------\n(.*?)8<--------8<--------8<--------8<-------- END: create cluster 8<--------8<--------8<--------8<--------\n`)
	matches := createClusterRe.FindStringSubmatch(buildLogStr)
	if len(matches) >= 2 {
		buildSummaryStr = "FAILURE: create cluster failed!"
		buildDetailsStr = matches[1]
	} else {
		buildSummaryStr = "FAILURE: Could not find create cluster?"
	}

	return buildFinished, buildSummaryStr, buildDetailsStr, nil
}

// gatherTestRun gathers test run information
func gatherTestRun(client *http.Client, spyglassLink SpyglassLink, ciTypeStr string, ciStats *CIStats) (string, string, error) {
	testSummaryStr := ""
	testDetailsStr := ""

	junitDirURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/openshift-e2e-libvirt-test/artifacts/junit/"
	junitDirStr, err := getURLString(client, junitDirURL)
	if err != nil {
		return testSummaryStr, testDetailsStr, err
	}

	filenameRe := regexp.MustCompile(`test-failures-summary_[^.]*\.json`)
	matches := filenameRe.FindStringSubmatch(junitDirStr)
	if len(matches) == 0 {
		testSummaryStr = "ERROR: Could not find test-failures-summary_*.json?"
		return testSummaryStr, testDetailsStr, nil
	}

	testFailureFilename := matches[0]
	junitURL := "https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs" + spyglassLink.SpyglassLink[8:] + "/artifacts/" + ciTypeStr + "/openshift-e2e-libvirt-test/artifacts/junit/" + testFailureFilename
	junitStr, err := getURLString(client, junitURL)
	if err != nil {
		return testSummaryStr, testDetailsStr, err
	}

	var testFailureSummary TestFailureSummary
	if err := json.Unmarshal([]byte(junitStr), &testFailureSummary); err != nil {
		return testSummaryStr, testDetailsStr, err
	}

	if len(testFailureSummary.Tests) == 0 {
		testSummaryStr = "SUCCESS: All tests succeeded!"
		ciStats.GreenRuns++
	} else {
		testSummaryStr = "FAILURE: Failing tests:"
		for _, test := range testFailureSummary.Tests {
			testDetailsStr += test.Test.Name + "\n"
		}
	}

	return testSummaryStr, testDetailsStr, nil
}

// fromISOFormat attempts to parse a date string using multiple ISO 8601 formats.
// It tries formats with varying precision (microseconds, seconds, date-only) to
// accommodate different input styles from command-line arguments.
// This flexibility allows users to specify dates as "2023-07-20" or "2023-07-20T15:04:05Z".
// Returns the parsed time in UTC, or an error if no format matches.
func fromISOFormat(dateStr string) (time.Time, error) {
	formats := []string{
		"2006-01-02T15:04:05.999999Z",
		"2006-01-02T15:04:05Z",
		"2006-01-02T15:04:05.999999",
		"2006-01-02T15:04:05",
		"2006-01-02",
	}

	for _, format := range formats {
		t, err := time.Parse(format, dateStr)
		if err == nil {
			return t, nil
		}
	}

	return time.Time{}, fmt.Errorf("unable to parse date: %s", dateStr)
}

// encodeString prepares a string for CSV output by escaping newline characters.
// CSV format doesn't handle multi-line cell content well, so newlines are converted
// to the literal string "\n" to keep each record on a single line.
// This ensures proper CSV parsing by spreadsheet applications.
func encodeString(input string) string {
	return strings.ReplaceAll(input, "\n", "\\n")
}

// processURL processes a single Prow CI job history URL and extracts job data.
// This is the main processing function that:
// 1. Parses the URL to extract CI version and type information
// 2. Iterates through job history pages (following "Older Runs" links)
// 4. Collects build and test results for each matching job
// 5. Outputs results in either human-readable or CSV format
// The function continues pagination until no more jobs match the date criteria.
func processURL(args *Args, ciStats *CIStats, url string, afterDt, beforeDt time.Time, csvWriter *csv.Writer) error {
	fmt.Fprintf(infoFp, "INFO: For URL %s\n", url)
	fmt.Fprintf(infoFp, "INFO: Finding CI runs between %s and %s\n", afterDt, beforeDt)
	fmt.Fprintln(infoFp)

	// Parse URL components to extract base URL and CI job name
	// Expected format: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/<job-name>
	// Remove trailing slash if present
	url = strings.TrimSuffix(url, "/")
	parts := strings.Split(url, "/")
	baseURLStr := parts[0] + "//" + parts[2]
	idx := strings.LastIndex(url, "/")
	ciStr := url[idx+1:]

	// Extract CI version (e.g., "4.12", "5.0") and type (e.g., "powervc-1") from job name
	// Job name format: periodic-ci-openshift-release-master-nightly-4.12-e2e-metal-ipi-ovn-ipv6
	// or: periodic-ci-openshift-multiarch-main-nightly-5.0-ocp-e2e-ovn-powervc-multi-p-p
	ciInfoRe := regexp.MustCompile(`([^0-9].*)-([0-9]+\.[0-9]+)-(.*)`)
	matches := ciInfoRe.FindStringSubmatch(ciStr)
	if len(matches) < 4 {
		fmt.Fprintln(infoFp, "ERROR: ci_info_re didn't match?")
		return fmt.Errorf("failed to parse CI string")
	}

	ciVersionStr := matches[2] // OpenShift version (e.g., "4.12", "4.13")
	ciTypeStr := matches[3]    // CI type/platform (e.g., "powervc-1", "powervc-2")

	// Create HTTP client with cookie jar for session management across requests
	jar, _ := cookiejar.New(nil)
	client := &http.Client{
		Jar: jar,
	}

	// Main pagination loop: process current page, then follow "Older Runs" link
	for {
		processedAny := false // Track if we processed any jobs on this page

		resp, err := client.Get(url)
		if err != nil {
			return err
		}

		doc, err := goquery.NewDocumentFromReader(resp.Body)
		resp.Body.Close()
		if err != nil {
			return err
		}

		// Find the "Older Runs" pagination link to continue to previous jobs
		// This link appears at the bottom of the job history page
		var olderHref string
		doc.Find("td").Each(func(i int, s *goquery.Selection) {
			if strings.Contains(s.Text(), "Older Runs") {
				s.Find("a").Each(func(j int, a *goquery.Selection) {
					if href, exists := a.Attr("href"); exists {
						olderHref = href
					}
				})
			}
		})

		// Find and process the allBuilds JavaScript array embedded in the page
		// This array contains metadata for all jobs displayed on the current page
		doc.Find("script").Each(func(i int, s *goquery.Selection) {
			scriptText := s.Text()
			if !strings.Contains(scriptText, "var allBuilds") {
				return
			}

			tableRe := regexp.MustCompile(`var allBuilds = (\[[^\]]+\]);`)
			matches := tableRe.FindStringSubmatch(scriptText)
			if len(matches) < 2 {
				return
			}

			var spyglassLinks []SpyglassLink
			if err := json.Unmarshal([]byte(matches[1]), &spyglassLinks); err != nil {
				return
			}

			// Process each job entry from the allBuilds array
			for _, spyglassLink := range spyglassLinks {
				buildSummaryStr := ""
				buildDetailsStr := ""
				testSummaryStr := ""
				testDetailsStr := ""

				// Construct full Spyglass URL for this job
				jobURL := "https://prow.ci.openshift.org" + spyglassLink.SpyglassLink

				// Filter by date range: skip jobs outside the specified time window
				include, err := includeWithDate(client, afterDt, beforeDt, spyglassLink, ciTypeStr)
				if err != nil || !include {
					continue
				}

				// Job passed all filters - process it
				processedAny = true
				ciStats.NumDeploys++

				// Print job header with separator line
				fmt.Fprintf(infoFp, "INFO: 8<--------8<--------8<--------8<--------8<--------8<--------8<--------8<--------\n")
				fmt.Fprintf(infoFp, "INFO: URL:  %s\n", jobURL)

				// Gather deployment/build results
				buildFinished, buildSummaryStr, buildDetailsStr, err := gatherBuildRun(client, spyglassLink, ciTypeStr)
				if err != nil {
					continue
				}

				// Output build results unless user only wants test status
				if !args.TestStatusOnly {
					if !args.CSV {
						fmt.Fprintf(outputFp, "%s\n%s", buildSummaryStr, buildDetailsStr)
					}
				}

				// If deployment succeeded, gather test results (unless user only wants deploy status)
				if buildFinished.Result == "SUCCESS" {
					ciStats.DeploysSucceeded++

					if !args.DeployStatusOnly {
						testSummaryStr, testDetailsStr, err = gatherTestRun(client, spyglassLink, ciTypeStr, ciStats)
						if err == nil && !args.CSV {
							fmt.Fprintf(outputFp, "%s\n%s\n", testSummaryStr, testDetailsStr)
						}
					} else {
						fmt.Fprintln(outputFp)
					}
				} else {
					if !args.CSV {
						fmt.Fprintln(outputFp)
					}
				}

				// Write CSV row if CSV output is enabled
				if args.CSV {
					testDetailsStr = strings.TrimSuffix(testDetailsStr, "\n")
					csvRow := []string{
						encodeString(jobURL),
						encodeString(buildSummaryStr),
						encodeString(buildDetailsStr),
						encodeString(testSummaryStr),
						encodeString(testDetailsStr),
					}
					csvWriter.Write(csvRow)
					fmt.Fprintln(infoFp)
				}
			}
		})

		// Stop pagination if no "Older Runs" link exists (reached the end)
		if olderHref == "" {
			break
		}

		// Stop pagination if we didn't process any jobs on this page
		// This means all remaining jobs are outside our date range
		if !processedAny {
			break
		}

		// Continue to the next page of older job runs
		url = baseURLStr + olderHref
	}

	_ = ciVersionStr // Suppress unused variable warning (may be used in future enhancements)

	return nil
}

// Args holds all command-line arguments and configuration options.
// It uses pointer receivers to allow flag package to modify values directly.
type Args struct {
	AfterStr         string   // Start date for filtering jobs (ISO 8601 format)
	BeforeStr        string   // End date for filtering jobs (ISO 8601 format)
	CSV              bool     // Enable CSV output format
	DeployStatusOnly bool     // Only report deployment status (skip test results)
	LastNDays        int      // Filter to last N days (alternative to AfterStr/BeforeStr)
	Output           string   // Output file path (empty = stdout)
	TestStatusOnly   bool     // Only report test status (skip deployment details)
	Today            bool     // Filter to today's jobs only
	URLs             []string // List of Prow job history URLs to process
	Yesterday        bool     // Filter to yesterday's jobs only
}

// main is the entry point for the JobHistory tool.
// It parses command-line arguments, validates date ranges, processes each CI URL,
// and outputs aggregated statistics about deployment success and test pass rates.
func main() {
	args := &Args{}

	// Custom usage function to document URL requirement
	flag.Usage = func() {
		fmt.Fprintf(os.Stderr, "Usage: %s [OPTIONS] URL [URL...]\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Analyze OpenShift CI job history from Prow for PowerVS deployments.\n\n")
		fmt.Fprintf(os.Stderr, "Required Arguments:\n")
		fmt.Fprintf(os.Stderr, "  URL    One or more Prow job history URLs to analyze\n")
		fmt.Fprintf(os.Stderr, "         Format: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/<job-name>\n\n")
		fmt.Fprintf(os.Stderr, "Options (must be specified BEFORE URLs):\n")
		flag.PrintDefaults()
		fmt.Fprintf(os.Stderr, "\nExamples:\n")
		fmt.Fprintf(os.Stderr, "  # Analyze today's jobs (note: flags come before URL)\n")
		fmt.Fprintf(os.Stderr, "  %s --today https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-...\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  # Analyze last 7 days with CSV output\n")
		fmt.Fprintf(os.Stderr, "  %s --last-n-days 7 --csv --output results.csv <URL>\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "  # Filter by zone\n")
		fmt.Fprintf(os.Stderr, "  %s --zone lon04 --yesterday <URL>\n\n", os.Args[0])
		fmt.Fprintf(os.Stderr, "Note: All options must be specified before the URL(s).\n")
	}

	// Define all command-line flags with both long and short forms
	flag.StringVar(&args.AfterStr, "after-date", "", "Only queries after this date")
	flag.StringVar(&args.AfterStr, "a", "", "Only queries after this date (shorthand)")
	flag.StringVar(&args.BeforeStr, "before-date", "", "Only queries before this date")
	flag.StringVar(&args.BeforeStr, "b", "", "Only queries before this date (shorthand)")
	flag.BoolVar(&args.CSV, "csv", false, "Output in CSV format")
	flag.BoolVar(&args.CSV, "c", false, "Output in CSV format (shorthand)")
	flag.BoolVar(&args.DeployStatusOnly, "deploy-status-only", false, "Only show deploy failures")
	flag.BoolVar(&args.DeployStatusOnly, "d", false, "Only show deploy failures (shorthand)")
	flag.IntVar(&args.LastNDays, "last-n-days", 0, "Only queries for the last n days")
	flag.IntVar(&args.LastNDays, "l", 0, "Only queries for the last n days (shorthand)")
	flag.StringVar(&args.Output, "output", "", "The filename for output")
	flag.StringVar(&args.Output, "o", "", "The filename for output (shorthand)")
	flag.BoolVar(&args.TestStatusOnly, "test-status-only", false, "Only show test failures")
	flag.BoolVar(&args.TestStatusOnly, "t", false, "Only show test failures (shorthand)")
	flag.BoolVar(&args.Today, "today", false, "Only queries for today")
	flag.BoolVar(&args.Yesterday, "yesterday", false, "Only queries for yesterday")

	showVersion := flag.Bool("version", false, "Display the version of this program")
	flag.BoolVar(showVersion, "v", false, "Display the version of this program (shorthand)")

	flag.Parse()

	// Handle version flag
	if *showVersion {
		fmt.Printf("JobHistory %s\n", version)
		os.Exit(0)
	}

	// Collect positional arguments as URLs
	args.URLs = flag.Args()
	if len(args.URLs) == 0 {
		fmt.Fprintln(os.Stderr, "ERROR: At least one URL is required")
		flag.Usage()
		os.Exit(1)
	}

	// Check if any positional arguments look like flags (common user error)
	for _, arg := range args.URLs {
		if strings.HasPrefix(arg, "-") || strings.HasPrefix(arg, "--") {
			fmt.Fprintf(os.Stderr, "ERROR: Flag '%s' appears after URL(s)\n", arg)
			fmt.Fprintln(os.Stderr, "All options must be specified BEFORE the URL arguments.")
			fmt.Fprintln(os.Stderr, "")
			flag.Usage()
			os.Exit(1)
		}
	}

	// Date range validation and calculation
	// Supports multiple modes: --today, --yesterday, --last-n-days, or explicit --after-date/--before-date
	var afterDt, beforeDt time.Time
	var err error

	// Process --today flag: set date range to current day (00:00:00 to 23:59:59 UTC)
	if args.Today {
		if args.AfterStr != "" || args.BeforeStr != "" || args.Yesterday || args.LastNDays > 0 {
			fmt.Fprintln(infoFp, "ERROR: Cannot combine --today with other date options")
			os.Exit(1)
		}
		now := time.Now()
		afterDt = time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)
		beforeDt = time.Date(now.Year(), now.Month(), now.Day(), 23, 59, 59, 999999999, time.UTC)
	} else if args.Yesterday {
		// Process --yesterday flag: set date range to previous day
		if args.AfterStr != "" || args.BeforeStr != "" || args.Today || args.LastNDays > 0 {
			fmt.Fprintln(infoFp, "ERROR: Cannot combine --yesterday with other date options")
			os.Exit(1)
		}
		yesterday := time.Now().AddDate(0, 0, -1)
		afterDt = time.Date(yesterday.Year(), yesterday.Month(), yesterday.Day(), 0, 0, 0, 0, time.UTC)
		beforeDt = time.Date(yesterday.Year(), yesterday.Month(), yesterday.Day(), 23, 59, 59, 999999999, time.UTC)
	} else if args.LastNDays > 0 {
		// Process --last-n-days flag: set date range from N days ago to today
		if args.Today || args.Yesterday {
			fmt.Fprintln(infoFp, "ERROR: Cannot combine --last-n-days with other date options")
			os.Exit(1)
		}
		lastDate := time.Now().AddDate(0, 0, -(args.LastNDays - 1))
		afterDt = time.Date(lastDate.Year(), lastDate.Month(), lastDate.Day(), 0, 0, 0, 0, time.UTC)
		now := time.Now()
		beforeDt = time.Date(now.Year(), now.Month(), now.Day(), 23, 59, 59, 999999999, time.UTC)
	} else {
		// Default: no start date (beginning of time), end date is now
		afterDt = time.Time{}
		beforeDt = time.Now().UTC()
	}

	// Override with explicit --after-date if provided
	if args.AfterStr != "" {
		afterDt, err = fromISOFormat(args.AfterStr)
		if err != nil {
			fmt.Fprintf(infoFp, "ERROR: Unknown formatted date %s\n", args.AfterStr)
			os.Exit(1)
		}
	}

	// Override with explicit --before-date if provided
	if args.BeforeStr != "" {
		beforeDt, err = fromISOFormat(args.BeforeStr)
		if err != nil {
			fmt.Fprintf(infoFp, "ERROR: Unknown formatted date %s\n", args.BeforeStr)
			os.Exit(1)
		}
	}

	// Setup output file handles
	// Redirect output to file if --output flag is specified
	if args.Output != "" {
		f, err := os.Create(args.Output)
		if err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: Cannot create output file: %v\n", err)
			os.Exit(1)
		}
		defer f.Close()
		outputFp = f
		// In CSV mode, keep info messages on stderr; otherwise redirect to file
		if !args.CSV {
			infoFp = f
		}
	}

	// Initialize CSV writer if CSV output is requested
	var csvWriter *csv.Writer
	if args.CSV {
		csvWriter = csv.NewWriter(outputFp)
		defer csvWriter.Flush()
		// Write CSV header row
		csvWriter.Write([]string{
			"Job URL",
			"Zone",
			"Build summary",
			"Build details",
			"Test summary",
			"Test details",
		})
	}

	// Initialize statistics tracker
	ciStats := &CIStats{}

	// Process each URL provided on the command line
	for _, url := range args.URLs {
		// Validate URL format - must be a Prow job history URL
		if !strings.Contains(url, "https://prow.ci.openshift.org/job-history/gs/test-platform-results/logs/") {
			fmt.Fprintln(infoFp, "ERROR: unknown CI URL")
			os.Exit(1)
		}

		// Process this URL and accumulate statistics
		if err := processURL(args, ciStats, url, afterDt, beforeDt, csvWriter); err != nil {
			fmt.Fprintf(infoFp, "ERROR: %v\n", err)
		}
	}

	// Print final summary statistics
	fmt.Fprintln(infoFp, "Finished")
	if !args.TestStatusOnly {
		fmt.Fprintf(infoFp, "%d/%d deploys succeeded\n", ciStats.DeploysSucceeded, ciStats.NumDeploys)
	}
	if !args.DeployStatusOnly {
		fmt.Fprintf(infoFp, "%d/%d e2e green runs\n", ciStats.GreenRuns, ciStats.NumDeploys)
	}
}

// Made with Bob
