# .github/workflows/release.yaml

name: Build and release Go Project

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        # List of GOOS and GOARCH pairs from `go tool dist list`
        goosarch:
        # - 'linux/ppc64le'
          - 'linux/amd64'
    steps:
    - name: Print release tag
      run: echo "Building release for tag ${{ github.ref_name }}"

    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7 # Recommended action to set up Go environment
      with:
        go-version-file: 'go.mod' # Automatically detects the Go version from go.mod

    - name: Build
      run: make build

    - name: Release
      run: |
        make release
        make checksums

    - name: Release binaries
      uses: softprops/action-gh-release@v3
      # https://github.com/softprops/action-gh-release
      with:
        files: |
          dist/ocp-ipi-powervc-${{ github.ref_name }}.tgz
          dist/ocp-ipi-powervc-${{ github.ref_name }}.tgz.sha256
          dist/ocp-ipi-powervc-darwin-amd64
          dist/ocp-ipi-powervc-darwin-amd64.sha256
          dist/ocp-ipi-powervc-darwin-arm64
          dist/ocp-ipi-powervc-darwin-arm64.sha256
          dist/ocp-ipi-powervc-linux-amd64
          dist/ocp-ipi-powervc-linux-amd64.sha256
          dist/ocp-ipi-powervc-linux-arm64
          dist/ocp-ipi-powervc-linux-arm64.sha256
          dist/ocp-ipi-powervc-linux-ppc64le
          dist/ocp-ipi-powervc-linux-ppc64le.sha256
          dist/JobHistory-darwin-amd64
          dist/JobHistory-darwin-amd64.sha256
          dist/JobHistory-darwin-arm64
          dist/JobHistory-darwin-arm64.sha256
          dist/JobHistory-linux-amd64
          dist/JobHistory-linux-amd64.sha256
          dist/JobHistory-linux-arm64
          dist/JobHistory-linux-arm64.sha256
          dist/JobHistory-linux-ppc64le
          dist/JobHistory-linux-ppc64le.sha256
          dist/UploadRhcos-darwin-amd64
          dist/UploadRhcos-darwin-amd64.sha256
          dist/UploadRhcos-darwin-arm64
          dist/UploadRhcos-darwin-arm64.sha256
          dist/UploadRhcos-linux-amd64
          dist/UploadRhcos-linux-amd64.sha256
          dist/UploadRhcos-linux-arm64
          dist/UploadRhcos-linux-arm64.sha256
          dist/UploadRhcos-linux-ppc64le
          dist/UploadRhcos-linux-ppc64le.sha256
          dist/UploadCentos-darwin-amd64
          dist/UploadCentos-darwin-amd64.sha256
          dist/UploadCentos-darwin-arm64
          dist/UploadCentos-darwin-arm64.sha256
          dist/UploadCentos-linux-amd64
          dist/UploadCentos-linux-amd64.sha256
          dist/UploadCentos-linux-arm64
          dist/UploadCentos-linux-arm64.sha256
          dist/UploadCentos-linux-ppc64le
          dist/UploadCentos-linux-ppc64le.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided secret

    - name: Release scripts
      uses: softprops/action-gh-release@v3
      # https://github.com/softprops/action-gh-release
      with:
        files: |
          dist/create-cluster.sh
          dist/create-cluster.sh.sha256
          dist/delete-cluster.sh
          dist/delete-cluster.sh.sha256
          dist/console.sh
          dist/console.sh.sha256
          dist/ssh.sh
          dist/ssh.sh.sha256
          dist/current-servers.sh
          dist/current-servers.sh.sha256
          dist/list-bastions.sh
          dist/list-bastions.sh.sha256
          dist/print-stream-json.sh
          dist/print-stream-json.sh.sha256
          dist/upload-centos.sh
          dist/upload-centos.sh.sha256
          dist/upload-rhcos.sh
          dist/upload-rhcos.sh.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided secret
